server:
  port: 10240

spring:
  application:
    name: CONFIG

  cloud:
    config:
      server:
        git:
          uri: git@github.com:nhnacademy-be9-E2BS/e2bs-config-repo.git
          ignoreLocalSshSettings: true
          strictHostKeyChecking: false
          default-label: main
          search-paths: .
          privateKey: ${GIT_PRIVATE_KY}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka
  instance:
    prefer-ip-address: true

## Spring Cloud Config 설정 파일 내용 자동 갱신
management:
  endpoints:
    web:
      exposure:
        include: "*"